server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/"
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000